### ISSUE TITLE
Unable to override the default email/phone

### ISSUE THREAD

**Issue by sco-pi** [saadnpq/npq-hugo#1]
Hi @saadnpq, thanks for making this theme, I've just looking at getting started with a personal site in Hugo and it perfectly fits my requirements.

At the moment I don't want to have my contact information (phone/email) in the footer, I've tried to remove these from my `config.toml` but it looks to have been overridden by the defaults in the `config.toml` in the theme.

As I'm just using your repo as a git submodule, I was wondering if there is a change that could be made to the default/example config that would allow for this use case?

Thanks,
Scott.

**Comment by saadnpq** [comment]
hello Scott, sorry for the late reply, i hate GitHub's notification system.

unfortunately I've been busy for a while now but i am going to work again on this theme soon as it needs some refurbishment. i will keep you updated as i start and definitely i will look first at this issue and your PR.

Thanks.

**Comment by saadjsct** [comment]
i have just pushed a commit that should fix this issue, i changed the name of the example config provided. 
please tell me if this didn't fix the issue for you and i will reopen it
